export const GET_ERRORS = 'GET_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const GET_USER = 'GET_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_LOGIN_ERRORS = 'GET_LOGIN_ERRORS';
export const EMAIL_VERIFIED_PASSWORD_RESET = 'EMAIL_VERIFIED_PASSWORD_RESET';
export const GET_SUCCESS_RESET = 'GET_SUCCESS_RESET';
